"""
Django settings for apps project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '386s^k&ywiv6!f7f^u^d&8ikq2b5jl&mjk)t*2u)b$d729oz(a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apply',
    'ckeditor',
    'ckeditor_uploader',
    'pure_pagination'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myproject',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
# HERE = os.path.dirname(os.path.abspath(__file__))
# HERE = os.path.join(HERE, '../')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, '../static/'),
)

MEDIA_ROOT = BASE_DIR    #os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
CKEDITOR_UPLOAD_PATH = 'upload/'
CKEDITOR_IMAGE_BACKEND = 'pillow'



FITMENT = ( #装修类型
    ('0', '--请选择--'),
    ('1', '简单装修'),
    ('2', '中等装修'),
    ('3', '精装修'),
    ('4', '豪华装修'),
    ('5', '毛坯')
)
ORIENTATION = ( #朝向
    ('0', '--请选择--'),
    ('1', '东北'),
    ('2', '东南'),
    ('3', '东西'),
    ('4', '北'),
    ('5', '南'),
    ('6', '南北'),
    ('7', '西'),
    ('8', '西北'),
    ('9', '西南'),
    ('10', '东')
)

STOREY_PROPERTY = ( # 楼层类型
    ('0', '--请选择--'),
    ('1', '低层'),
    ('2', '中层'),
    ('3', '高层'),
    ('4', '地下')
)
PAY_METHOD = ( # 支付方式
    ('0', '--请选择--'),
    ('1', '半年付不押'),
    ('2', '半年付押一'),
    ('3', '年付'),
    ('4', '年付不押'),
    ('5', '年付押一'),
    ('6', '押一付一'),
    ('7', '押一付三'),
    ('8', '押一付二'),
    ('9', '押二付一'),
    ('10', '押二付三'),
    ('11', '押二付二'),
    ('12', '面议'),
    ('13', '半年付')
)